{% set name = "xphyle" %}
{% set version = "4.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 25c5801c11e675c35fb5317c81ae3f13791bdb2b1c7ededc552ee2ce7eb96ae7

build:
  skip: true  # [not unix]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools_scm
  run:
    - pokrok
    - python

test:
  imports:
    - xphyle
  requires:
    - pytest
    - pytest-cov

about:
  home: https://github.com/jdidion/xphyle
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Utilities for working with files.
  dev_url: https://github.com/jdidion/xphyle

extra:
  recipe-maintainers:
    - jdidion
    - rhpvorderman
