{% set name = "xphyle" %}
{% set version = "4.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6a31246a26dcd835677e1315a51f828375eab71acf2fcb1ac0657147b45caa0c

build:
  skip: true  # [not unix]
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools_scm
  run:
    - pokrok
    - python

test:
  imports:
    - xphyle
  requires:
    - pytest
    - pytest-cov

about:
  home: https://github.com/jdidion/xphyle
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Utilities for working with files.
  dev_url: https://github.com/jdidion/xphyle

extra:
  recipe-maintainers:
    - jdidion
    - rhpvorderman
